name       : luminance-hdr
version    : 2.6.0
release    : 20
source     :
    - https://github.com/LuminanceHDR/LuminanceHDR/archive/v.2.6.0.tar.gz : c325e0a78a9f2bbfc1af683e09a4eeb412674615a2b17a29f4626962ac3e518c
license    : GPL-2.0-only
component  : multimedia.graphics
summary    : a complete opensource solution for HDR photography
description: |
    Open source graphical user interface application that aims to provide a workflow for HDR imaging.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineCore)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(cfitsio)
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/OpenEXR-instead-of-ilmbase.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
