name       : luminance-hdr
version    : 2.5.0
release    : 1
source     :
    - http://sourceforge.net/projects/qtpfsgui/files/luminance/2.5.0/luminance-hdr-2.5.0.tar.bz2 : f5caf3316d1763058b1b0f2a6963df34465fbf918b7abeee5245a51fc14a7942
license    : GPL-2.0
component  : multimedia.graphics
summary    : a complete opensource solution for HDR photography
description: |
    Open source graphical user interface application that aims to provide a workflow for HDR imaging.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineCore)
    - pkgconfig(Qt5WebKit)
    - libboost-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
