name       : luminance-hdr
version    : 2.5.1
release    : 6
source     :
    - https://netcologne.dl.sourceforge.net/project/qtpfsgui/luminance/2.5.1/luminance-hdr-2.5.1.tar.bz2 : a8986e0afba434a2e9da7e8aed19cdb763fedc8de2655bdb496c4ee9d3f41696
license    : GPL-2.0-only
component  : multimedia.graphics
summary    : a complete opensource solution for HDR photography
description: |
    Open source graphical user interface application that aims to provide a workflow for HDR imaging.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineCore)
    - pkgconfig(Qt5WebKit)
    - libboost-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
